window.microbiologyPastData = {
  "meta": {
    "paperRecords": 8,
    "identifiableItems": 184,
    "rawItems": 13,
    "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx"
  },
  "items": [
    {
      "id": "past-bbf34ee47455",
      "paperId": "2023-clinical5",
      "paperLabel": "2023 临五",
      "year": 2023,
      "qno": "A1 1",
      "type": "choice",
      "prompt": "G+菌特有分子（磷壁酸）",
      "corePoint": "细胞壁/肽聚糖维持细菌形态",
      "chapter": "第1章 细菌形态与结构",
      "coverage": "A",
      "exercisePages": "16-23",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 1
    },
    {
      "id": "past-653a7c2a15e3",
      "paperId": "2023-clinical5",
      "paperLabel": "2023 临五",
      "year": 2023,
      "qno": "A1 2",
      "type": "choice",
      "prompt": "灭菌效果以杀灭芽胞为标准",
      "corePoint": "芽胞及灭菌指标",
      "chapter": "第1章 细菌形态与结构",
      "coverage": "A",
      "exercisePages": "17-23",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 2
    },
    {
      "id": "past-cc7c206c84ba",
      "paperId": "2023-clinical5",
      "paperLabel": "2023 临五",
      "year": 2023,
      "qno": "A1 3",
      "type": "choice",
      "prompt": "细菌分裂方式",
      "corePoint": "细菌二分裂",
      "chapter": "第2章 细菌生理",
      "coverage": "B",
      "exercisePages": "26-34",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 3
    },
    {
      "id": "past-c11d7f3a148a",
      "paperId": "2023-clinical5",
      "paperLabel": "2023 临五",
      "year": 2023,
      "qno": "A1 4",
      "type": "choice",
      "prompt": "朊病毒灭活条件",
      "corePoint": "朊粒灭活",
      "chapter": "第34章 朊粒",
      "coverage": "B",
      "exercisePages": "250-253",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 4
    },
    {
      "id": "past-0eb4725f8fc8",
      "paperId": "2023-clinical5",
      "paperLabel": "2023 临五",
      "year": 2023,
      "qno": "A1 5",
      "type": "choice",
      "prompt": "肉毒毒素作用部位",
      "corePoint": "肉毒毒素作用部位与临床表现",
      "chapter": "第12章 厌氧性细菌",
      "coverage": "A",
      "exercisePages": "102-106",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 5
    },
    {
      "id": "past-60ab1ee1ac3b",
      "paperId": "2023-clinical5",
      "paperLabel": "2023 临五",
      "year": 2023,
      "qno": "A1 6",
      "type": "choice",
      "prompt": "抑酸治疗后腹泻病例/幽门螺杆菌描述",
      "corePoint": "幽门螺杆菌、尿素酶及致病物质",
      "chapter": "第11章 螺杆菌属",
      "coverage": "A",
      "exercisePages": "98-100",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 6
    },
    {
      "id": "past-f82e89c6ab13",
      "paperId": "2023-clinical5",
      "paperLabel": "2023 临五",
      "year": 2023,
      "qno": "A1 7",
      "type": "choice",
      "prompt": "粪-口传播的病原体",
      "corePoint": "粪-口传播的肝炎病毒",
      "chapter": "第28章 肝炎病毒",
      "coverage": "A",
      "exercisePages": "211-219",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 7
    },
    {
      "id": "past-569575099363",
      "paperId": "2023-clinical5",
      "paperLabel": "2023 临五",
      "year": 2023,
      "qno": "A1 8",
      "type": "choice",
      "prompt": "以荚膜为主要致病物质的病原体",
      "corePoint": "荚膜与抗吞噬/致病性",
      "chapter": "第1、6章",
      "coverage": "B",
      "exercisePages": "17-23, 50-61",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 8
    },
    {
      "id": "past-639ceaebc1e5",
      "paperId": "2023-clinical5",
      "paperLabel": "2023 临五",
      "year": 2023,
      "qno": "A1 9",
      "type": "choice",
      "prompt": "引发霍乱样症状的大肠埃希菌",
      "corePoint": "ETEC与霍乱样腹泻",
      "chapter": "第9章 肠杆菌科",
      "coverage": "A",
      "exercisePages": "85-92",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 9
    },
    {
      "id": "past-9ac2b5428c5a",
      "paperId": "2023-clinical5",
      "paperLabel": "2023 临五",
      "year": 2023,
      "qno": "A1 10",
      "type": "choice",
      "prompt": "吕氏培养基培养白喉棒状杆菌",
      "corePoint": "培养基与病原菌配对",
      "chapter": "第7-21章",
      "coverage": "B",
      "exercisePages": "65-70, 85-167",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 10
    },
    {
      "id": "past-5ef4ab83235a",
      "paperId": "2023-clinical5",
      "paperLabel": "2023 临五",
      "year": 2023,
      "qno": "A1 11",
      "type": "choice",
      "prompt": "食用海鲜相关病原体",
      "corePoint": "副溶血性弧菌与海产品",
      "chapter": "第10章 弧菌属",
      "coverage": "A",
      "exercisePages": "93-98",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 11
    },
    {
      "id": "past-8b2e74d5af85",
      "paperId": "2023-clinical5",
      "paperLabel": "2023 临五",
      "year": 2023,
      "qno": "A1 12",
      "type": "choice",
      "prompt": "SSPE病原体",
      "corePoint": "麻疹病毒与SSPE",
      "chapter": "第23、25章",
      "coverage": "A",
      "exercisePages": "177-183, 193-197",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 12
    },
    {
      "id": "past-f091a2d4b58e",
      "paperId": "2023-clinical5",
      "paperLabel": "2023 临五",
      "year": 2023,
      "qno": "A1 13",
      "type": "choice",
      "prompt": "汹涌发酵见于何种微生物",
      "corePoint": "汹涌发酵",
      "chapter": "第12章 厌氧性细菌",
      "coverage": "A",
      "exercisePages": "102-106",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 13
    },
    {
      "id": "past-131523aabb94",
      "paperId": "2023-clinical5",
      "paperLabel": "2023 临五",
      "year": 2023,
      "qno": "A1 14",
      "type": "choice",
      "prompt": "孕妇感染致胎儿畸形",
      "corePoint": "风疹与先天畸形",
      "chapter": "第25章 呼吸道病毒",
      "coverage": "A",
      "exercisePages": "193-197",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 14
    },
    {
      "id": "past-91f760907607",
      "paperId": "2023-clinical5",
      "paperLabel": "2023 临五",
      "year": 2023,
      "qno": "A1 15",
      "type": "choice",
      "prompt": "哪种病毒核酸具有感染性",
      "corePoint": "感染性核酸/正链RNA",
      "chapter": "第22章 病毒基本性状",
      "coverage": "A",
      "exercisePages": "170-174",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 15
    },
    {
      "id": "past-9ee3f838fa3a",
      "paperId": "2023-clinical5",
      "paperLabel": "2023 临五",
      "year": 2023,
      "qno": "A1 16",
      "type": "choice",
      "prompt": "手足口病病原体",
      "corePoint": "手足口病病原体",
      "chapter": "第26章 肠道病毒",
      "coverage": "A",
      "exercisePages": "198-202",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 16
    },
    {
      "id": "past-4c4323572863",
      "paperId": "2023-clinical5",
      "paperLabel": "2023 临五",
      "year": 2023,
      "qno": "A1 17",
      "type": "choice",
      "prompt": "携带逆转录酶的病毒",
      "corePoint": "HBV结构、核酸与逆转录",
      "chapter": "第28章 肝炎病毒",
      "coverage": "B",
      "exercisePages": "211-219",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 17
    },
    {
      "id": "past-a3fc5f648d41",
      "paperId": "2023-clinical5",
      "paperLabel": "2023 临五",
      "year": 2023,
      "qno": "A1 附1",
      "type": "choice",
      "prompt": "肥达试验",
      "corePoint": "肥达试验",
      "chapter": "第7、9章",
      "coverage": "A",
      "exercisePages": "68-70, 85-92",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 18
    },
    {
      "id": "past-4a1c0374521d",
      "paperId": "2023-clinical5",
      "paperLabel": "2023 临五",
      "year": 2023,
      "qno": "A1 附2",
      "type": "choice",
      "prompt": "乙肝抗原抗体检查",
      "corePoint": "HBV血清标志物",
      "chapter": "第28章 肝炎病毒",
      "coverage": "A",
      "exercisePages": "211-219",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 19
    },
    {
      "id": "past-78b3b034a3f6",
      "paperId": "2023-clinical5",
      "paperLabel": "2023 临五",
      "year": 2023,
      "qno": "A1 附3",
      "type": "choice",
      "prompt": "流感HA与NA",
      "corePoint": "流感病毒HA/NA",
      "chapter": "第25章 呼吸道病毒",
      "coverage": "B",
      "exercisePages": "193-197",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 20
    },
    {
      "id": "past-6a5b44cb839e",
      "paperId": "2023-clinical5",
      "paperLabel": "2023 临五",
      "year": 2023,
      "qno": "X型 1",
      "type": "raw",
      "prompt": "感染后可终身携带的病原体",
      "corePoint": "潜伏感染",
      "chapter": "第23章 病毒感染与免疫",
      "coverage": "A",
      "exercisePages": "177-183",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 21
    },
    {
      "id": "past-ef017055cc00",
      "paperId": "2023-clinical5",
      "paperLabel": "2023 临五",
      "year": 2023,
      "qno": "X型 2",
      "type": "raw",
      "prompt": "呼吸道飞沫传播病原体",
      "corePoint": "呼吸道传播病毒",
      "chapter": "第25章 呼吸道病毒",
      "coverage": "B",
      "exercisePages": "193-197",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 22
    },
    {
      "id": "past-1bd5aa804a69",
      "paperId": "2023-clinical5",
      "paperLabel": "2023 临五",
      "year": 2023,
      "qno": "X型 3",
      "type": "raw",
      "prompt": "导致神经系统后遗症的病原体",
      "corePoint": "神经毒素",
      "chapter": "第6、12章",
      "coverage": "A",
      "exercisePages": "51-61, 101-108",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 23
    },
    {
      "id": "past-a3b959c16e62",
      "paperId": "2023-clinical5",
      "paperLabel": "2023 临五",
      "year": 2023,
      "qno": "X型 4",
      "type": "raw",
      "prompt": "流感容易大流行的原因",
      "corePoint": "流感抗原性转变/大流行",
      "chapter": "第25章 呼吸道病毒",
      "coverage": "B",
      "exercisePages": "193-197",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 24
    },
    {
      "id": "past-52e58e912523",
      "paperId": "2023-clinical5",
      "paperLabel": "2023 临五",
      "year": 2023,
      "qno": "名词解释 1",
      "type": "term",
      "prompt": "SPA（葡萄球菌A蛋白）",
      "corePoint": "SPA（葡萄球菌A蛋白）",
      "chapter": "第7、8章",
      "coverage": "A",
      "exercisePages": "69-81",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 25
    },
    {
      "id": "past-829a236870b2",
      "paperId": "2023-clinical5",
      "paperLabel": "2023 临五",
      "year": 2023,
      "qno": "名词解释 2",
      "type": "term",
      "prompt": "MIC",
      "corePoint": "MIC最小抑菌浓度",
      "chapter": "第5章 细菌耐药性",
      "coverage": "B",
      "exercisePages": "46-48",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 26
    },
    {
      "id": "past-3564e9198bc2",
      "paperId": "2023-clinical5",
      "paperLabel": "2023 临五",
      "year": 2023,
      "qno": "名词解释 3",
      "type": "term",
      "prompt": "DAA",
      "corePoint": "DAA直接抗病毒药物",
      "chapter": "第28章 肝炎病毒",
      "coverage": "C",
      "exercisePages": "216",
      "judgment": "仅补概念，不足以单独应试",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 27
    },
    {
      "id": "past-a9e0f8098394",
      "paperId": "2023-clinical5",
      "paperLabel": "2023 临五",
      "year": 2023,
      "qno": "名词解释 4",
      "type": "term",
      "prompt": "latent infection",
      "corePoint": "潜伏感染",
      "chapter": "第23章 病毒感染与免疫",
      "coverage": "A",
      "exercisePages": "177-183",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 28
    },
    {
      "id": "past-7d19e02e9661",
      "paperId": "2023-clinical5",
      "paperLabel": "2023 临五",
      "year": 2023,
      "qno": "简答/病例 1",
      "type": "case",
      "prompt": "列举三种人畜共患病及所致疾病",
      "corePoint": "人畜共患/动物源性细菌",
      "chapter": "第15章 动物源性细菌",
      "coverage": "B",
      "exercisePages": "117-125",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 29
    },
    {
      "id": "past-462cd4110a27",
      "paperId": "2023-clinical5",
      "paperLabel": "2023 临五",
      "year": 2023,
      "qno": "简答/病例 2",
      "type": "case",
      "prompt": "HPV传播、危害及高价疫苗意义",
      "corePoint": "HPV高低危型、危害与疫苗",
      "chapter": "第23、33章",
      "coverage": "C",
      "exercisePages": "177-183, 245-249",
      "judgment": "仅补概念，不足以单独应试",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 30
    },
    {
      "id": "past-e87d7b2dc237",
      "paperId": "2023-clinical5",
      "paperLabel": "2023 临五",
      "year": 2023,
      "qno": "简答/病例 3",
      "type": "case",
      "prompt": "幽门螺杆菌、快速尿素酶试验及致病机制",
      "corePoint": "幽门螺杆菌、尿素酶及致病物质",
      "chapter": "第11章 螺杆菌属",
      "coverage": "A",
      "exercisePages": "98-100",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 31
    },
    {
      "id": "past-516336cbc842",
      "paperId": "2023-preventive-forensic",
      "paperLabel": "2023 预防/法医",
      "year": 2023,
      "qno": "A1 1",
      "type": "choice",
      "prompt": "维持细菌形态的结构",
      "corePoint": "细胞壁/肽聚糖维持细菌形态",
      "chapter": "第1章 细菌形态与结构",
      "coverage": "A",
      "exercisePages": "16-23",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 1
    },
    {
      "id": "past-45b7c2528253",
      "paperId": "2023-preventive-forensic",
      "paperLabel": "2023 预防/法医",
      "year": 2023,
      "qno": "A1 2",
      "type": "choice",
      "prompt": "机会致病菌",
      "corePoint": "机会致病菌",
      "chapter": "第6章 细菌感染与免疫",
      "coverage": "A",
      "exercisePages": "50-61",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 2
    },
    {
      "id": "past-0dd8e61c4817",
      "paperId": "2023-preventive-forensic",
      "paperLabel": "2023 预防/法医",
      "year": 2023,
      "qno": "A1 3",
      "type": "choice",
      "prompt": "依靠性菌毛的基因转移方式",
      "corePoint": "性菌毛与接合",
      "chapter": "第1、4章",
      "coverage": "A",
      "exercisePages": "19-23, 39-44",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 3
    },
    {
      "id": "past-0a5c615d0d39",
      "paperId": "2023-preventive-forensic",
      "paperLabel": "2023 预防/法医",
      "year": 2023,
      "qno": "A1 4",
      "type": "choice",
      "prompt": "完全/不完全溶血",
      "corePoint": "链球菌α/β/γ溶血",
      "chapter": "第8章 球菌",
      "coverage": "A",
      "exercisePages": "72-80",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 4
    },
    {
      "id": "past-a4fba6c53683",
      "paperId": "2023-preventive-forensic",
      "paperLabel": "2023 预防/法医",
      "year": 2023,
      "qno": "A1 5",
      "type": "choice",
      "prompt": "白喉棒状杆菌与心肌炎",
      "corePoint": "白喉棒状杆菌及毒素并发症",
      "chapter": "第16章 其他细菌",
      "coverage": "B",
      "exercisePages": "125-139",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 5
    },
    {
      "id": "past-2c600b750000",
      "paperId": "2023-preventive-forensic",
      "paperLabel": "2023 预防/法医",
      "year": 2023,
      "qno": "A1 6",
      "type": "choice",
      "prompt": "梅毒确证试验",
      "corePoint": "梅毒血清学筛查与确证",
      "chapter": "第21章 螺旋体",
      "coverage": "B",
      "exercisePages": "162-167",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 6
    },
    {
      "id": "past-aacba20f4e27",
      "paperId": "2023-preventive-forensic",
      "paperLabel": "2023 预防/法医",
      "year": 2023,
      "qno": "A1 7",
      "type": "choice",
      "prompt": "人群暴发胃肠炎病原",
      "corePoint": "诺如病毒聚集性胃肠炎",
      "chapter": "第27章 急性胃肠炎病毒",
      "coverage": "A",
      "exercisePages": "205-209",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 7
    },
    {
      "id": "past-17c47f863bb2",
      "paperId": "2023-preventive-forensic",
      "paperLabel": "2023 预防/法医",
      "year": 2023,
      "qno": "A1 8",
      "type": "choice",
      "prompt": "轮状病毒特征",
      "corePoint": "轮状病毒",
      "chapter": "第27章 急性胃肠炎病毒",
      "coverage": "A",
      "exercisePages": "205-209",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 8
    },
    {
      "id": "past-69134ae7dd5d",
      "paperId": "2023-preventive-forensic",
      "paperLabel": "2023 预防/法医",
      "year": 2023,
      "qno": "A1 9",
      "type": "choice",
      "prompt": "HBV血清标志物",
      "corePoint": "HBV血清标志物",
      "chapter": "第28章 肝炎病毒",
      "coverage": "A",
      "exercisePages": "211-219",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 9
    },
    {
      "id": "past-017974772b0e",
      "paperId": "2023-preventive-forensic",
      "paperLabel": "2023 预防/法医",
      "year": 2023,
      "qno": "A1 10",
      "type": "choice",
      "prompt": "不能导致出血热的病毒",
      "corePoint": "出血热病毒",
      "chapter": "第30章 出血热病毒",
      "coverage": "B",
      "exercisePages": "226-230",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 10
    },
    {
      "id": "past-9dedcbf0c86e",
      "paperId": "2023-preventive-forensic",
      "paperLabel": "2023 预防/法医",
      "year": 2023,
      "qno": "A1 11",
      "type": "choice",
      "prompt": "HPV高危型与低危型",
      "corePoint": "HPV高低危型、危害与疫苗",
      "chapter": "第23、33章",
      "coverage": "C",
      "exercisePages": "177-183, 245-249",
      "judgment": "仅补概念，不足以单独应试",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 11
    },
    {
      "id": "past-21a1a3eb08b4",
      "paperId": "2023-preventive-forensic",
      "paperLabel": "2023 预防/法医",
      "year": 2023,
      "qno": "A1 12",
      "type": "choice",
      "prompt": "新冠病毒介导感染的蛋白",
      "corePoint": "SARS-CoV-2刺突蛋白",
      "chapter": "习题集未检出",
      "coverage": "D",
      "exercisePages": "未检出",
      "judgment": "习题集无有效覆盖",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 12
    },
    {
      "id": "past-e95e5a91c54f",
      "paperId": "2023-preventive-forensic",
      "paperLabel": "2023 预防/法医",
      "year": 2023,
      "qno": "A1 13",
      "type": "choice",
      "prompt": "朊粒由宿主细胞基因编码",
      "corePoint": "朊粒及其宿主编码蛋白",
      "chapter": "第34章 朊粒",
      "coverage": "B",
      "exercisePages": "250-253",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 13
    },
    {
      "id": "past-236ebab0c958",
      "paperId": "2023-preventive-forensic",
      "paperLabel": "2023 预防/法医",
      "year": 2023,
      "qno": "A2 1",
      "type": "choice",
      "prompt": "诺如病毒病例选择",
      "corePoint": "诺如病毒聚集性胃肠炎",
      "chapter": "第27章 急性胃肠炎病毒",
      "coverage": "A",
      "exercisePages": "205-209",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 14
    },
    {
      "id": "past-5ce5e80a8e98",
      "paperId": "2023-preventive-forensic",
      "paperLabel": "2023 预防/法医",
      "year": 2023,
      "qno": "X型 1",
      "type": "raw",
      "prompt": "慢发病毒感染",
      "corePoint": "慢发病毒感染",
      "chapter": "第23章 病毒感染与免疫",
      "coverage": "A",
      "exercisePages": "177-183",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 15
    },
    {
      "id": "past-88c91ce0df94",
      "paperId": "2023-preventive-forensic",
      "paperLabel": "2023 预防/法医",
      "year": 2023,
      "qno": "X型 2",
      "type": "raw",
      "prompt": "幽门螺杆菌致病物质",
      "corePoint": "幽门螺杆菌、尿素酶及致病物质",
      "chapter": "第11章 螺杆菌属",
      "coverage": "A",
      "exercisePages": "98-100",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 16
    },
    {
      "id": "past-bb5475c5ee83",
      "paperId": "2023-preventive-forensic",
      "paperLabel": "2023 预防/法医",
      "year": 2023,
      "qno": "名词解释 1",
      "type": "term",
      "prompt": "pyrogenic exotoxin",
      "corePoint": "致热外毒素/猩红热毒素",
      "chapter": "第8章 球菌",
      "coverage": "A",
      "exercisePages": "72-81",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 17
    },
    {
      "id": "past-5799e55ccfe6",
      "paperId": "2023-preventive-forensic",
      "paperLabel": "2023 预防/法医",
      "year": 2023,
      "qno": "名词解释 2",
      "type": "term",
      "prompt": "coagulase",
      "corePoint": "凝固酶",
      "chapter": "第8章 球菌",
      "coverage": "A",
      "exercisePages": "71-81",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 18
    },
    {
      "id": "past-05e7954cc464",
      "paperId": "2023-preventive-forensic",
      "paperLabel": "2023 预防/法医",
      "year": 2023,
      "qno": "名词解释 3",
      "type": "term",
      "prompt": "stormy fermentation",
      "corePoint": "汹涌发酵",
      "chapter": "第12章 厌氧性细菌",
      "coverage": "A",
      "exercisePages": "102-106",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 19
    },
    {
      "id": "past-b8611daa0d42",
      "paperId": "2023-preventive-forensic",
      "paperLabel": "2023 预防/法医",
      "year": 2023,
      "qno": "名词解释 4",
      "type": "term",
      "prompt": "reverse transcriptase",
      "corePoint": "逆转录酶",
      "chapter": "第32章 逆转录病毒",
      "coverage": "B",
      "exercisePages": "238-244",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 20
    },
    {
      "id": "past-57f3c438f4ee",
      "paperId": "2023-preventive-forensic",
      "paperLabel": "2023 预防/法医",
      "year": 2023,
      "qno": "名词解释 5",
      "type": "term",
      "prompt": "cccDNA",
      "corePoint": "cccDNA",
      "chapter": "习题集未检出",
      "coverage": "D",
      "exercisePages": "未检出",
      "judgment": "习题集无有效覆盖",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 21
    },
    {
      "id": "past-48363de9f7f6",
      "paperId": "2023-preventive-forensic",
      "paperLabel": "2023 预防/法医",
      "year": 2023,
      "qno": "名词解释 6",
      "type": "term",
      "prompt": "cytopathic effect（回忆不确定）",
      "corePoint": "病毒感染细胞的结局/CPE",
      "chapter": "第23、24章",
      "coverage": "B",
      "exercisePages": "176-191",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 22
    },
    {
      "id": "past-7ce6578d03fe",
      "paperId": "2023-preventive-forensic",
      "paperLabel": "2023 预防/法医",
      "year": 2023,
      "qno": "简答 1",
      "type": "short",
      "prompt": "不同菌属食物中毒细菌及致病物质",
      "corePoint": "食物中毒细菌及致病物质",
      "chapter": "第6、8-12章",
      "coverage": "B",
      "exercisePages": "55-61, 75-80, 85-108",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 23
    },
    {
      "id": "past-4a5ddeedb19f",
      "paperId": "2023-preventive-forensic",
      "paperLabel": "2023 预防/法医",
      "year": 2023,
      "qno": "简答 2",
      "type": "short",
      "prompt": "结核分枝杆菌实验室检查流程",
      "corePoint": "结核分枝杆菌实验室检查流程",
      "chapter": "第13章 分枝杆菌属",
      "coverage": "C",
      "exercisePages": "108-114",
      "judgment": "仅补概念，不足以单独应试",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 24
    },
    {
      "id": "past-0bed0a7b473f",
      "paperId": "2023-preventive-forensic",
      "paperLabel": "2023 预防/法医",
      "year": 2023,
      "qno": "简答 3",
      "type": "short",
      "prompt": "toxemia定义并举例",
      "corePoint": "毒血症",
      "chapter": "第6章 细菌感染与免疫",
      "coverage": "A",
      "exercisePages": "50-61",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 25
    },
    {
      "id": "past-94358be61258",
      "paperId": "2023-preventive-forensic",
      "paperLabel": "2023 预防/法医",
      "year": 2023,
      "qno": "简答 4",
      "type": "short",
      "prompt": "灭活与减毒活疫苗比较",
      "corePoint": "减毒活疫苗与灭活疫苗比较",
      "chapter": "第7、24章",
      "coverage": "A",
      "exercisePages": "67-70, 185-191",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 26
    },
    {
      "id": "past-3218801ca61b",
      "paperId": "2023-preventive-forensic",
      "paperLabel": "2023 预防/法医",
      "year": 2023,
      "qno": "病例 1",
      "type": "case",
      "prompt": "东南亚旅行后腹泻：病原、机制、传播途径",
      "corePoint": "霍乱弧菌、机制与传播",
      "chapter": "第10章 弧菌属",
      "coverage": "A",
      "exercisePages": "93-98",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 27
    },
    {
      "id": "past-7bc7d370887a",
      "paperId": "2023-preventive-forensic",
      "paperLabel": "2023 预防/法医",
      "year": 2023,
      "qno": "病例 2",
      "type": "case",
      "prompt": "家庭HBV血清标志物、预防妻子感染及后续HDV",
      "corePoint": "HDV重叠/联合感染",
      "chapter": "第28章 肝炎病毒",
      "coverage": "B",
      "exercisePages": "211-219",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 28
    },
    {
      "id": "past-4a400bb00297",
      "paperId": "2022-clinical8",
      "paperLabel": "2022 临八",
      "year": 2022,
      "qno": "名词解释 1",
      "type": "term",
      "prompt": "pyrogenic exotoxin",
      "corePoint": "致热外毒素/猩红热毒素",
      "chapter": "第8章 球菌",
      "coverage": "A",
      "exercisePages": "72-81",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 1
    },
    {
      "id": "past-57a1140a05b6",
      "paperId": "2022-clinical8",
      "paperLabel": "2022 临八",
      "year": 2022,
      "qno": "名词解释 2",
      "type": "term",
      "prompt": "coagulase",
      "corePoint": "凝固酶",
      "chapter": "第8章 球菌",
      "coverage": "A",
      "exercisePages": "71-81",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 2
    },
    {
      "id": "past-3fdfd86e93d6",
      "paperId": "2022-clinical8",
      "paperLabel": "2022 临八",
      "year": 2022,
      "qno": "名词解释 3",
      "type": "term",
      "prompt": "cccDNA",
      "corePoint": "cccDNA",
      "chapter": "习题集未检出",
      "coverage": "D",
      "exercisePages": "未检出",
      "judgment": "习题集无有效覆盖",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 3
    },
    {
      "id": "past-0b6f91ccd121",
      "paperId": "2022-clinical8",
      "paperLabel": "2022 临八",
      "year": 2022,
      "qno": "名词解释 4",
      "type": "term",
      "prompt": "reverse transcriptase",
      "corePoint": "逆转录酶",
      "chapter": "第32章 逆转录病毒",
      "coverage": "B",
      "exercisePages": "238-244",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 4
    },
    {
      "id": "past-7d046072a3dc",
      "paperId": "2022-clinical8",
      "paperLabel": "2022 临八",
      "year": 2022,
      "qno": "名词解释 5",
      "type": "term",
      "prompt": "stormy fermentation",
      "corePoint": "汹涌发酵",
      "chapter": "第12章 厌氧性细菌",
      "coverage": "A",
      "exercisePages": "102-106",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 5
    },
    {
      "id": "past-5cb28f6f6015",
      "paperId": "2022-clinical8",
      "paperLabel": "2022 临八",
      "year": 2022,
      "qno": "名词解释 6",
      "type": "term",
      "prompt": "CPE",
      "corePoint": "病毒感染细胞的结局/CPE",
      "chapter": "第23、24章",
      "coverage": "B",
      "exercisePages": "176-191",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 6
    },
    {
      "id": "past-3bc24a2cb461",
      "paperId": "2022-clinical8",
      "paperLabel": "2022 临八",
      "year": 2022,
      "qno": "简答 1",
      "type": "short",
      "prompt": "四种消化系统致病细菌及症状",
      "corePoint": "食物中毒细菌及致病物质",
      "chapter": "第6、8-12章",
      "coverage": "B",
      "exercisePages": "55-61, 75-80, 85-108",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 7
    },
    {
      "id": "past-efd583542570",
      "paperId": "2022-clinical8",
      "paperLabel": "2022 临八",
      "year": 2022,
      "qno": "简答 2",
      "type": "short",
      "prompt": "病毒血症并列举四种",
      "corePoint": "病毒血症与免疫特点",
      "chapter": "第23章 病毒感染与免疫",
      "coverage": "B",
      "exercisePages": "178-183",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 8
    },
    {
      "id": "past-b3644e258eb2",
      "paperId": "2022-clinical8",
      "paperLabel": "2022 临八",
      "year": 2022,
      "qno": "简答 3",
      "type": "short",
      "prompt": "结核杆菌实验室诊断",
      "corePoint": "结核分枝杆菌实验室检查流程",
      "chapter": "第13章 分枝杆菌属",
      "coverage": "C",
      "exercisePages": "108-114",
      "judgment": "仅补概念，不足以单独应试",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 9
    },
    {
      "id": "past-ad3ff3204dfa",
      "paperId": "2022-clinical8",
      "paperLabel": "2022 临八",
      "year": 2022,
      "qno": "简答 4",
      "type": "short",
      "prompt": "灭活与减毒疫苗比较",
      "corePoint": "减毒活疫苗与灭活疫苗比较",
      "chapter": "第7、24章",
      "coverage": "A",
      "exercisePages": "67-70, 185-191",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 10
    },
    {
      "id": "past-ef9f294e7c2b",
      "paperId": "2022-clinical8",
      "paperLabel": "2022 临八",
      "year": 2022,
      "qno": "病例 1",
      "type": "case",
      "prompt": "东南亚旅行后水样便：霍乱、机制及传播",
      "corePoint": "霍乱弧菌、机制与传播",
      "chapter": "第10章 弧菌属",
      "coverage": "A",
      "exercisePages": "93-98",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 11
    },
    {
      "id": "past-08335b4c79af",
      "paperId": "2022-clinical8",
      "paperLabel": "2022 临八",
      "year": 2022,
      "qno": "病例 2",
      "type": "case",
      "prompt": "登革热症状、重症机制和防治",
      "corePoint": "登革热、ADE与防治",
      "chapter": "第29章 虫媒病毒",
      "coverage": "B",
      "exercisePages": "220-225",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 12
    },
    {
      "id": "past-e198114f988f",
      "paperId": "2022-clinical5",
      "paperLabel": "2022 临五",
      "year": 2022,
      "qno": "A1 1",
      "type": "choice",
      "prompt": "性传播病原体",
      "corePoint": "梅毒血清学筛查与确证",
      "chapter": "第21章 螺旋体",
      "coverage": "B",
      "exercisePages": "162-167",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 1
    },
    {
      "id": "past-23a96b2b584f",
      "paperId": "2022-clinical5",
      "paperLabel": "2022 临五",
      "year": 2022,
      "qno": "A1 2",
      "type": "choice",
      "prompt": "SSPE病原体",
      "corePoint": "麻疹病毒与SSPE",
      "chapter": "第23、25章",
      "coverage": "A",
      "exercisePages": "177-183, 193-197",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 2
    },
    {
      "id": "past-31535cea4909",
      "paperId": "2022-clinical5",
      "paperLabel": "2022 临五",
      "year": 2022,
      "qno": "A1 3",
      "type": "choice",
      "prompt": "猩红热病原体",
      "corePoint": "致热外毒素/猩红热毒素",
      "chapter": "第8章 球菌",
      "coverage": "A",
      "exercisePages": "72-81",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 3
    },
    {
      "id": "past-dbe7a93254e6",
      "paperId": "2022-clinical5",
      "paperLabel": "2022 临五",
      "year": 2022,
      "qno": "A1 4",
      "type": "choice",
      "prompt": "LPS组成",
      "corePoint": "内毒素结构与生物学作用",
      "chapter": "第6章 细菌感染与免疫",
      "coverage": "A",
      "exercisePages": "50-61",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 4
    },
    {
      "id": "past-d4000a0d8cf4",
      "paperId": "2022-clinical5",
      "paperLabel": "2022 临五",
      "year": 2022,
      "qno": "A1 5",
      "type": "choice",
      "prompt": "悬滴法检查病原体",
      "corePoint": "霍乱弧菌、机制与传播",
      "chapter": "第10章 弧菌属",
      "coverage": "A",
      "exercisePages": "93-98",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 5
    },
    {
      "id": "past-2f01429826f0",
      "paperId": "2022-clinical5",
      "paperLabel": "2022 临五",
      "year": 2022,
      "qno": "A1 7",
      "type": "choice",
      "prompt": "导致胎儿畸形的病毒",
      "corePoint": "风疹与先天畸形",
      "chapter": "第25章 呼吸道病毒",
      "coverage": "A",
      "exercisePages": "193-197",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 6
    },
    {
      "id": "past-95092dd9eff3",
      "paperId": "2022-clinical5",
      "paperLabel": "2022 临五",
      "year": 2022,
      "qno": "A1 8",
      "type": "choice",
      "prompt": "口腔正常菌群",
      "corePoint": "机会致病菌",
      "chapter": "第6章 细菌感染与免疫",
      "coverage": "A",
      "exercisePages": "50-61",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 7
    },
    {
      "id": "past-dc7284cb59e1",
      "paperId": "2022-clinical5",
      "paperLabel": "2022 临五",
      "year": 2022,
      "qno": "A1 9",
      "type": "choice",
      "prompt": "疱疹性咽峡炎病原体",
      "corePoint": "疱疹性咽峡炎",
      "chapter": "第26章 肠道病毒",
      "coverage": "A",
      "exercisePages": "198-202",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 8
    },
    {
      "id": "past-e21a607660cf",
      "paperId": "2022-clinical5",
      "paperLabel": "2022 临五",
      "year": 2022,
      "qno": "A1 10",
      "type": "choice",
      "prompt": "出血性结肠炎病原体",
      "corePoint": "EHEC与出血性结肠炎",
      "chapter": "第9章 肠杆菌科",
      "coverage": "A",
      "exercisePages": "85-92",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 9
    },
    {
      "id": "past-9dd53a188ef2",
      "paperId": "2022-clinical5",
      "paperLabel": "2022 临五",
      "year": 2022,
      "qno": "A1 11",
      "type": "choice",
      "prompt": "HAV疫苗与慢性感染",
      "corePoint": "粪-口传播的肝炎病毒",
      "chapter": "第28章 肝炎病毒",
      "coverage": "A",
      "exercisePages": "211-219",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 10
    },
    {
      "id": "past-fb1ab4b9f066",
      "paperId": "2022-clinical5",
      "paperLabel": "2022 临五",
      "year": 2022,
      "qno": "A1 12",
      "type": "choice",
      "prompt": "IAV易变异原因",
      "corePoint": "流感抗原性转变/大流行",
      "chapter": "第25章 呼吸道病毒",
      "coverage": "B",
      "exercisePages": "193-197",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 11
    },
    {
      "id": "past-2090fb3d7cd8",
      "paperId": "2022-clinical5",
      "paperLabel": "2022 临五",
      "year": 2022,
      "qno": "A1 13",
      "type": "choice",
      "prompt": "无鞭毛细菌",
      "corePoint": "细菌毒力与致病物质",
      "chapter": "第6章 细菌感染与免疫",
      "coverage": "A",
      "exercisePages": "50-61",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 12
    },
    {
      "id": "past-5875e17c557d",
      "paperId": "2022-clinical5",
      "paperLabel": "2022 临五",
      "year": 2022,
      "qno": "A1 14",
      "type": "choice",
      "prompt": "巧克力平板培养的细菌",
      "corePoint": "培养基与病原菌配对",
      "chapter": "第7-21章",
      "coverage": "B",
      "exercisePages": "65-70, 85-167",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 13
    },
    {
      "id": "past-b07dc2c1338b",
      "paperId": "2022-clinical5",
      "paperLabel": "2022 临五",
      "year": 2022,
      "qno": "X型 1",
      "type": "raw",
      "prompt": "肿瘤相关病毒",
      "corePoint": "肿瘤相关病毒",
      "chapter": "第23、32、33章",
      "coverage": "B",
      "exercisePages": "177-183, 238-249",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 14
    },
    {
      "id": "past-47bacc71fb86",
      "paperId": "2022-clinical5",
      "paperLabel": "2022 临五",
      "year": 2022,
      "qno": "X型 2",
      "type": "raw",
      "prompt": "HDV正确叙述",
      "corePoint": "HDV重叠/联合感染",
      "chapter": "第28章 肝炎病毒",
      "coverage": "B",
      "exercisePages": "211-219",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 15
    },
    {
      "id": "past-d3c16e37c780",
      "paperId": "2022-clinical5",
      "paperLabel": "2022 临五",
      "year": 2022,
      "qno": "X型 3",
      "type": "raw",
      "prompt": "呼吸道传播病原体",
      "corePoint": "呼吸道传播病毒",
      "chapter": "第25章 呼吸道病毒",
      "coverage": "B",
      "exercisePages": "193-197",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 16
    },
    {
      "id": "past-59b0e43b99c5",
      "paperId": "2022-clinical5",
      "paperLabel": "2022 临五",
      "year": 2022,
      "qno": "名词解释 1",
      "type": "term",
      "prompt": "viral receptor",
      "corePoint": "病毒受体",
      "chapter": "第22章 病毒基本性状",
      "coverage": "B",
      "exercisePages": "168-174",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 17
    },
    {
      "id": "past-9ed5819f8525",
      "paperId": "2022-clinical5",
      "paperLabel": "2022 临五",
      "year": 2022,
      "qno": "名词解释 2",
      "type": "term",
      "prompt": "hemagglutination",
      "corePoint": "血凝/血凝抑制试验",
      "chapter": "第24章 病毒检查与防治",
      "coverage": "A",
      "exercisePages": "188-191",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 18
    },
    {
      "id": "past-9cce0bf099de",
      "paperId": "2022-clinical5",
      "paperLabel": "2022 临五",
      "year": 2022,
      "qno": "简答 1",
      "type": "short",
      "prompt": "列举两种产生外毒素的细菌",
      "corePoint": "细菌毒力与致病物质",
      "chapter": "第6章 细菌感染与免疫",
      "coverage": "A",
      "exercisePages": "50-61",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 19
    },
    {
      "id": "past-8d5de1d6c7a8",
      "paperId": "2022-clinical5",
      "paperLabel": "2022 临五",
      "year": 2022,
      "qno": "简答 2",
      "type": "short",
      "prompt": "VZV感染特性及防治",
      "corePoint": "VZV感染特点与防治",
      "chapter": "第31章 疱疹病毒",
      "coverage": "B",
      "exercisePages": "232-237",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 20
    },
    {
      "id": "past-6603de4dfc9d",
      "paperId": "2022-clinical5",
      "paperLabel": "2022 临五",
      "year": 2022,
      "qno": "病例 1",
      "type": "case",
      "prompt": "HBV综合论述",
      "corePoint": "HBV血清标志物",
      "chapter": "第28章 肝炎病毒",
      "coverage": "A",
      "exercisePages": "211-219",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 21
    },
    {
      "id": "past-c12e18d89dcd",
      "paperId": "2022-dentistry",
      "paperLabel": "2022 口腔",
      "year": 2022,
      "qno": "A1 1",
      "type": "choice",
      "prompt": "维持细菌形态的细胞壁结构",
      "corePoint": "细胞壁/肽聚糖维持细菌形态",
      "chapter": "第1章 细菌形态与结构",
      "coverage": "A",
      "exercisePages": "16-23",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 1
    },
    {
      "id": "past-acca0497d1f3",
      "paperId": "2022-dentistry",
      "paperLabel": "2022 口腔",
      "year": 2022,
      "qno": "A1 2",
      "type": "choice",
      "prompt": "与基因水平转移相关的结构",
      "corePoint": "性菌毛与接合",
      "chapter": "第1、4章",
      "coverage": "A",
      "exercisePages": "19-23, 39-44",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 2
    },
    {
      "id": "past-8e29a2206a0b",
      "paperId": "2022-dentistry",
      "paperLabel": "2022 口腔",
      "year": 2022,
      "qno": "A1 3",
      "type": "choice",
      "prompt": "与黏附相关的细菌结构",
      "corePoint": "普通菌毛/黏附结构",
      "chapter": "第1、6章",
      "coverage": "A",
      "exercisePages": "17-23, 50-61",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 3
    },
    {
      "id": "past-bc03693da1d6",
      "paperId": "2022-dentistry",
      "paperLabel": "2022 口腔",
      "year": 2022,
      "qno": "A1 4",
      "type": "choice",
      "prompt": "培养基与细菌正确配对",
      "corePoint": "培养基与病原菌配对",
      "chapter": "第7-21章",
      "coverage": "B",
      "exercisePages": "65-70, 85-167",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 4
    },
    {
      "id": "past-83adff6e268c",
      "paperId": "2022-dentistry",
      "paperLabel": "2022 口腔",
      "year": 2022,
      "qno": "A1 5",
      "type": "choice",
      "prompt": "LT、ST、霍乱毒素和志贺毒素机制比较",
      "corePoint": "细菌毒力与致病物质",
      "chapter": "第6章 细菌感染与免疫",
      "coverage": "A",
      "exercisePages": "50-61",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 5
    },
    {
      "id": "past-671528828622",
      "paperId": "2022-dentistry",
      "paperLabel": "2022 口腔",
      "year": 2022,
      "qno": "A1 6",
      "type": "choice",
      "prompt": "抗生素滥用后肠炎病原",
      "corePoint": "机会致病菌",
      "chapter": "第6章 细菌感染与免疫",
      "coverage": "A",
      "exercisePages": "50-61",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 6
    },
    {
      "id": "past-188252b308fe",
      "paperId": "2022-dentistry",
      "paperLabel": "2022 口腔",
      "year": 2022,
      "qno": "A1 7",
      "type": "choice",
      "prompt": "梅毒初筛方法",
      "corePoint": "梅毒血清学筛查与确证",
      "chapter": "第21章 螺旋体",
      "coverage": "B",
      "exercisePages": "162-167",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 7
    },
    {
      "id": "past-4d99dbae197e",
      "paperId": "2022-dentistry",
      "paperLabel": "2022 口腔",
      "year": 2022,
      "qno": "A1 8",
      "type": "choice",
      "prompt": "可发生重配的病毒基因组",
      "corePoint": "重配",
      "chapter": "第22章 病毒基本性状",
      "coverage": "A",
      "exercisePages": "170-174",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 8
    },
    {
      "id": "past-836e3c9296eb",
      "paperId": "2022-dentistry",
      "paperLabel": "2022 口腔",
      "year": 2022,
      "qno": "A1 9",
      "type": "choice",
      "prompt": "肥皂可破坏的病毒",
      "corePoint": "包膜病毒对脂溶剂/肥皂敏感",
      "chapter": "第22章 病毒基本性状",
      "coverage": "A",
      "exercisePages": "168-174",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 9
    },
    {
      "id": "past-0e7c5be6f1d1",
      "paperId": "2022-dentistry",
      "paperLabel": "2022 口腔",
      "year": 2022,
      "qno": "A1 10",
      "type": "choice",
      "prompt": "鼠疫动物宿主/媒介",
      "corePoint": "鼠疫传播媒介与动物宿主",
      "chapter": "第15章 动物源性细菌",
      "coverage": "B",
      "exercisePages": "117-125",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 10
    },
    {
      "id": "past-b35410733b6b",
      "paperId": "2022-dentistry",
      "paperLabel": "2022 口腔",
      "year": 2022,
      "qno": "A1 11",
      "type": "choice",
      "prompt": "不会导致出血热的病毒",
      "corePoint": "出血热病毒",
      "chapter": "第30章 出血热病毒",
      "coverage": "B",
      "exercisePages": "226-230",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 11
    },
    {
      "id": "past-90a5ae79fd38",
      "paperId": "2022-dentistry",
      "paperLabel": "2022 口腔",
      "year": 2022,
      "qno": "A1 12",
      "type": "choice",
      "prompt": "游轮/学校聚集性呕吐腹泻病原（题1）",
      "corePoint": "诺如病毒聚集性胃肠炎",
      "chapter": "第27章 急性胃肠炎病毒",
      "coverage": "A",
      "exercisePages": "205-209",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 12
    },
    {
      "id": "past-417232a36670",
      "paperId": "2022-dentistry",
      "paperLabel": "2022 口腔",
      "year": 2022,
      "qno": "A1 13",
      "type": "choice",
      "prompt": "游轮/学校聚集性呕吐腹泻病原（题2）",
      "corePoint": "诺如病毒聚集性胃肠炎",
      "chapter": "第27章 急性胃肠炎病毒",
      "coverage": "A",
      "exercisePages": "205-209",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 13
    },
    {
      "id": "past-19f024af8912",
      "paperId": "2022-dentistry",
      "paperLabel": "2022 口腔",
      "year": 2022,
      "qno": "A1 14",
      "type": "choice",
      "prompt": "属于肠杆菌科的病原体",
      "corePoint": "肠杆菌科鉴别",
      "chapter": "第9章 肠杆菌科",
      "coverage": "A",
      "exercisePages": "85-92",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 14
    },
    {
      "id": "past-55628b909691",
      "paperId": "2022-dentistry",
      "paperLabel": "2022 口腔",
      "year": 2022,
      "qno": "A1 15",
      "type": "choice",
      "prompt": "轮状病毒错误叙述",
      "corePoint": "轮状病毒",
      "chapter": "第27章 急性胃肠炎病毒",
      "coverage": "A",
      "exercisePages": "205-209",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 15
    },
    {
      "id": "past-c87e066445ee",
      "paperId": "2022-dentistry",
      "paperLabel": "2022 口腔",
      "year": 2022,
      "qno": "A1 16",
      "type": "choice",
      "prompt": "机会性感染病原",
      "corePoint": "机会致病菌",
      "chapter": "第6章 细菌感染与免疫",
      "coverage": "A",
      "exercisePages": "50-61",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 16
    },
    {
      "id": "past-5aa82e0c48be",
      "paperId": "2022-dentistry",
      "paperLabel": "2022 口腔",
      "year": 2022,
      "qno": "A1 17",
      "type": "choice",
      "prompt": "HIV潜伏期特点",
      "corePoint": "HIV结构、潜伏期与致病",
      "chapter": "第32章 逆转录病毒",
      "coverage": "B",
      "exercisePages": "238-244",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 17
    },
    {
      "id": "past-17461176339c",
      "paperId": "2022-dentistry",
      "paperLabel": "2022 口腔",
      "year": 2022,
      "qno": "A2 1",
      "type": "choice",
      "prompt": "既往梅毒治疗后妊娠及母婴风险",
      "corePoint": "梅毒血清学筛查与确证",
      "chapter": "第21章 螺旋体",
      "coverage": "B",
      "exercisePages": "162-167",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 18
    },
    {
      "id": "past-cd000c8c2c16",
      "paperId": "2022-dentistry",
      "paperLabel": "2022 口腔",
      "year": 2022,
      "qno": "X型 1",
      "type": "raw",
      "prompt": "神经毒素致病",
      "corePoint": "神经毒素",
      "chapter": "第6、12章",
      "coverage": "A",
      "exercisePages": "51-61, 101-108",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 19
    },
    {
      "id": "past-4c86878b1a39",
      "paperId": "2022-dentistry",
      "paperLabel": "2022 口腔",
      "year": 2022,
      "qno": "X型 2",
      "type": "raw",
      "prompt": "慢发病毒感染",
      "corePoint": "慢发病毒感染",
      "chapter": "第23章 病毒感染与免疫",
      "coverage": "A",
      "exercisePages": "177-183",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 20
    },
    {
      "id": "past-7bc85e0a5a11",
      "paperId": "2022-dentistry",
      "paperLabel": "2022 口腔",
      "year": 2022,
      "qno": "X型 3",
      "type": "raw",
      "prompt": "幽门螺杆菌致病物质",
      "corePoint": "幽门螺杆菌、尿素酶及致病物质",
      "chapter": "第11章 螺杆菌属",
      "coverage": "A",
      "exercisePages": "98-100",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 21
    },
    {
      "id": "past-07dffa8616a7",
      "paperId": "2022-dentistry",
      "paperLabel": "2022 口腔",
      "year": 2022,
      "qno": "X型 4",
      "type": "raw",
      "prompt": "肿瘤相关病毒",
      "corePoint": "肿瘤相关病毒",
      "chapter": "第23、32、33章",
      "coverage": "B",
      "exercisePages": "177-183, 238-249",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 22
    },
    {
      "id": "past-c18400893343",
      "paperId": "2022-dentistry",
      "paperLabel": "2022 口腔",
      "year": 2022,
      "qno": "X型 5",
      "type": "raw",
      "prompt": "粪-口传播的肝炎病毒",
      "corePoint": "粪-口传播的肝炎病毒",
      "chapter": "第28章 肝炎病毒",
      "coverage": "A",
      "exercisePages": "211-219",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 23
    },
    {
      "id": "past-75183998f2eb",
      "paperId": "2022-dentistry",
      "paperLabel": "2022 口腔",
      "year": 2022,
      "qno": "名词解释 1",
      "type": "term",
      "prompt": "pyrogenic exotoxin",
      "corePoint": "致热外毒素/猩红热毒素",
      "chapter": "第8章 球菌",
      "coverage": "A",
      "exercisePages": "72-81",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 24
    },
    {
      "id": "past-31b712c7991d",
      "paperId": "2022-dentistry",
      "paperLabel": "2022 口腔",
      "year": 2022,
      "qno": "名词解释 2",
      "type": "term",
      "prompt": "coagulase",
      "corePoint": "凝固酶",
      "chapter": "第8章 球菌",
      "coverage": "A",
      "exercisePages": "71-81",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 25
    },
    {
      "id": "past-8ae618df45d7",
      "paperId": "2022-dentistry",
      "paperLabel": "2022 口腔",
      "year": 2022,
      "qno": "名词解释 3",
      "type": "term",
      "prompt": "stormy fermentation",
      "corePoint": "汹涌发酵",
      "chapter": "第12章 厌氧性细菌",
      "coverage": "A",
      "exercisePages": "102-106",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 26
    },
    {
      "id": "past-8a0d993a103a",
      "paperId": "2022-dentistry",
      "paperLabel": "2022 口腔",
      "year": 2022,
      "qno": "名词解释 4",
      "type": "term",
      "prompt": "cccDNA",
      "corePoint": "cccDNA",
      "chapter": "习题集未检出",
      "coverage": "D",
      "exercisePages": "未检出",
      "judgment": "习题集无有效覆盖",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 27
    },
    {
      "id": "past-45a86d35c8f9",
      "paperId": "2022-dentistry",
      "paperLabel": "2022 口腔",
      "year": 2022,
      "qno": "名词解释 5",
      "type": "term",
      "prompt": "reverse transcription",
      "corePoint": "逆转录酶",
      "chapter": "第32章 逆转录病毒",
      "coverage": "B",
      "exercisePages": "238-244",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 28
    },
    {
      "id": "past-3b38fdc9b18f",
      "paperId": "2022-dentistry",
      "paperLabel": "2022 口腔",
      "year": 2022,
      "qno": "名词解释 6",
      "type": "term",
      "prompt": "CPE",
      "corePoint": "病毒感染细胞的结局/CPE",
      "chapter": "第23、24章",
      "coverage": "B",
      "exercisePages": "176-191",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 29
    },
    {
      "id": "past-ed47285ede3e",
      "paperId": "2022-dentistry",
      "paperLabel": "2022 口腔",
      "year": 2022,
      "qno": "简答 1",
      "type": "short",
      "prompt": "四个不同属胃肠道致病细菌及致病物质",
      "corePoint": "食物中毒细菌及致病物质",
      "chapter": "第6、8-12章",
      "coverage": "B",
      "exercisePages": "55-61, 75-80, 85-108",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 30
    },
    {
      "id": "past-453f3b21b7c0",
      "paperId": "2022-dentistry",
      "paperLabel": "2022 口腔",
      "year": 2022,
      "qno": "简答 2",
      "type": "short",
      "prompt": "病毒血症、举例及疾病特点",
      "corePoint": "病毒血症与免疫特点",
      "chapter": "第23章 病毒感染与免疫",
      "coverage": "B",
      "exercisePages": "178-183",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 31
    },
    {
      "id": "past-ca60b82d0bc3",
      "paperId": "2022-dentistry",
      "paperLabel": "2022 口腔",
      "year": 2022,
      "qno": "简答 3",
      "type": "short",
      "prompt": "结核分枝杆菌实验检查",
      "corePoint": "结核分枝杆菌实验室检查流程",
      "chapter": "第13章 分枝杆菌属",
      "coverage": "C",
      "exercisePages": "108-114",
      "judgment": "仅补概念，不足以单独应试",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 32
    },
    {
      "id": "past-12a5ef3fbff0",
      "paperId": "2022-dentistry",
      "paperLabel": "2022 口腔",
      "year": 2022,
      "qno": "简答 4",
      "type": "short",
      "prompt": "减毒与灭活疫苗比较",
      "corePoint": "减毒活疫苗与灭活疫苗比较",
      "chapter": "第7、24章",
      "coverage": "A",
      "exercisePages": "67-70, 185-191",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 33
    },
    {
      "id": "past-7389a45f0e1b",
      "paperId": "2022-dentistry",
      "paperLabel": "2022 口腔",
      "year": 2022,
      "qno": "病例 1",
      "type": "case",
      "prompt": "猩红热后肾小球肾炎、机制及抗O原理",
      "corePoint": "链球菌感染后肾小球肾炎与抗O",
      "chapter": "第8章 球菌",
      "coverage": "B",
      "exercisePages": "72-81",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 34
    },
    {
      "id": "past-08d908795f3e",
      "paperId": "2022-dentistry",
      "paperLabel": "2022 口腔",
      "year": 2022,
      "qno": "病例 2",
      "type": "case",
      "prompt": "乙肝检查、血清标志物、传播预防及后续HDV",
      "corePoint": "HDV重叠/联合感染",
      "chapter": "第28章 肝炎病毒",
      "coverage": "B",
      "exercisePages": "211-219",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 35
    },
    {
      "id": "past-09319655bcd4",
      "paperId": "2022-preventive",
      "paperLabel": "2022 预防",
      "year": 2022,
      "qno": "名词解释 1",
      "type": "term",
      "prompt": "slow virus infection",
      "corePoint": "慢发病毒感染",
      "chapter": "第23章 病毒感染与免疫",
      "coverage": "A",
      "exercisePages": "177-183",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 1
    },
    {
      "id": "past-6a00c9cb8193",
      "paperId": "2022-preventive",
      "paperLabel": "2022 预防",
      "year": 2022,
      "qno": "名词解释 2",
      "type": "term",
      "prompt": "transduction",
      "corePoint": "转导",
      "chapter": "第3、4章",
      "coverage": "A",
      "exercisePages": "36-44",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 2
    },
    {
      "id": "past-37de8c3905da",
      "paperId": "2022-preventive",
      "paperLabel": "2022 预防",
      "year": 2022,
      "qno": "名词解释 3",
      "type": "term",
      "prompt": "virus life cycle（原文作virtual life cycle）",
      "corePoint": "病毒复制周期",
      "chapter": "第22章 病毒基本性状",
      "coverage": "A",
      "exercisePages": "168-174",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 3
    },
    {
      "id": "past-c82080906277",
      "paperId": "2022-preventive",
      "paperLabel": "2022 预防",
      "year": 2022,
      "qno": "名词解释 4",
      "type": "term",
      "prompt": "toxoid",
      "corePoint": "类毒素",
      "chapter": "第6、7章",
      "coverage": "A",
      "exercisePages": "53-61, 67-70",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 4
    },
    {
      "id": "past-ae5ece605fdb",
      "paperId": "2022-preventive",
      "paperLabel": "2022 预防",
      "year": 2022,
      "qno": "名词解释 5",
      "type": "term",
      "prompt": "reassortment",
      "corePoint": "重配",
      "chapter": "第22章 病毒基本性状",
      "coverage": "A",
      "exercisePages": "170-174",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 5
    },
    {
      "id": "past-3730ce288f93",
      "paperId": "2022-preventive",
      "paperLabel": "2022 预防",
      "year": 2022,
      "qno": "名词解释 6",
      "type": "term",
      "prompt": "bacterial L-form",
      "corePoint": "细菌L型",
      "chapter": "第1章 细菌形态与结构",
      "coverage": "A",
      "exercisePages": "16-23",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 6
    },
    {
      "id": "past-7b1bf2642015",
      "paperId": "2022-preventive",
      "paperLabel": "2022 预防",
      "year": 2022,
      "qno": "简答 1",
      "type": "short",
      "prompt": "HSV原发与复发病程",
      "corePoint": "HSV原发、潜伏与复发",
      "chapter": "第31章 疱疹病毒",
      "coverage": "A",
      "exercisePages": "232-237",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 7
    },
    {
      "id": "past-2c9c16829421",
      "paperId": "2022-preventive",
      "paperLabel": "2022 预防",
      "year": 2022,
      "qno": "简答 2",
      "type": "short",
      "prompt": "甲型流感/负链RNA复制特点",
      "corePoint": "甲型流感/负链RNA复制",
      "chapter": "第22、25章",
      "coverage": "B",
      "exercisePages": "168-174, 193-197",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 8
    },
    {
      "id": "past-027a723acd76",
      "paperId": "2022-preventive",
      "paperLabel": "2022 预防",
      "year": 2022,
      "qno": "简答 3",
      "type": "short",
      "prompt": "破伤风痉挛毒素与肉毒毒素比较",
      "corePoint": "破伤风与肉毒毒素比较",
      "chapter": "第12章 厌氧性细菌",
      "coverage": "B",
      "exercisePages": "102-106",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 9
    },
    {
      "id": "past-a72fc4f0aa47",
      "paperId": "2022-preventive",
      "paperLabel": "2022 预防",
      "year": 2022,
      "qno": "简答 4",
      "type": "short",
      "prompt": "内毒素结构和作用特点",
      "corePoint": "内毒素结构与生物学作用",
      "chapter": "第6章 细菌感染与免疫",
      "coverage": "A",
      "exercisePages": "50-61",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 10
    },
    {
      "id": "past-4f8e36b603ea",
      "paperId": "2021-clinical8",
      "paperLabel": "2021 临八",
      "year": 2021,
      "qno": "A2 37",
      "type": "choice",
      "prompt": "扁桃体肿痛三天的病原判断",
      "corePoint": "呼吸道传播病毒",
      "chapter": "第25章 呼吸道病毒",
      "coverage": "B",
      "exercisePages": "193-197",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 1
    },
    {
      "id": "past-5296f293cd84",
      "paperId": "2021-clinical8",
      "paperLabel": "2021 临八",
      "year": 2021,
      "qno": "名词解释 1",
      "type": "term",
      "prompt": "reassortment",
      "corePoint": "重配",
      "chapter": "第22章 病毒基本性状",
      "coverage": "A",
      "exercisePages": "170-174",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 2
    },
    {
      "id": "past-3b0d28be553f",
      "paperId": "2021-clinical8",
      "paperLabel": "2021 临八",
      "year": 2021,
      "qno": "名词解释 2",
      "type": "term",
      "prompt": "slow virus infection",
      "corePoint": "慢发病毒感染",
      "chapter": "第23章 病毒感染与免疫",
      "coverage": "A",
      "exercisePages": "177-183",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 3
    },
    {
      "id": "past-68846fb0b3f8",
      "paperId": "2021-clinical8",
      "paperLabel": "2021 临八",
      "year": 2021,
      "qno": "名词解释 3",
      "type": "term",
      "prompt": "virus life cycle",
      "corePoint": "病毒复制周期",
      "chapter": "第22章 病毒基本性状",
      "coverage": "A",
      "exercisePages": "168-174",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 4
    },
    {
      "id": "past-ca95cf2cf2cf",
      "paperId": "2021-clinical8",
      "paperLabel": "2021 临八",
      "year": 2021,
      "qno": "名词解释 4",
      "type": "term",
      "prompt": "toxoid",
      "corePoint": "类毒素",
      "chapter": "第6、7章",
      "coverage": "A",
      "exercisePages": "53-61, 67-70",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 5
    },
    {
      "id": "past-b56e2f9d5f1f",
      "paperId": "2021-clinical8",
      "paperLabel": "2021 临八",
      "year": 2021,
      "qno": "名词解释 5",
      "type": "term",
      "prompt": "transduction",
      "corePoint": "转导",
      "chapter": "第3、4章",
      "coverage": "A",
      "exercisePages": "36-44",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 6
    },
    {
      "id": "past-9a0bf06306c9",
      "paperId": "2021-clinical8",
      "paperLabel": "2021 临八",
      "year": 2021,
      "qno": "名词解释 6",
      "type": "term",
      "prompt": "L type bacteria",
      "corePoint": "细菌L型",
      "chapter": "第1章 细菌形态与结构",
      "coverage": "A",
      "exercisePages": "16-23",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 7
    },
    {
      "id": "past-8376be33ebfd",
      "paperId": "2021-clinical8",
      "paperLabel": "2021 临八",
      "year": 2021,
      "qno": "简答 1",
      "type": "short",
      "prompt": "内毒素结构和致病",
      "corePoint": "内毒素结构与生物学作用",
      "chapter": "第6章 细菌感染与免疫",
      "coverage": "A",
      "exercisePages": "50-61",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 8
    },
    {
      "id": "past-6e0ed2cfc949",
      "paperId": "2021-clinical8",
      "paperLabel": "2021 临八",
      "year": 2021,
      "qno": "简答 2",
      "type": "short",
      "prompt": "肉毒素与破伤风毒素比较",
      "corePoint": "破伤风与肉毒毒素比较",
      "chapter": "第12章 厌氧性细菌",
      "coverage": "B",
      "exercisePages": "102-106",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 9
    },
    {
      "id": "past-d3858b9f99cc",
      "paperId": "2021-clinical8",
      "paperLabel": "2021 临八",
      "year": 2021,
      "qno": "简答 3",
      "type": "short",
      "prompt": "HSV原发和复发感染",
      "corePoint": "HSV原发、潜伏与复发",
      "chapter": "第31章 疱疹病毒",
      "coverage": "A",
      "exercisePages": "232-237",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 10
    },
    {
      "id": "past-470935b6730b",
      "paperId": "2021-clinical8",
      "paperLabel": "2021 临八",
      "year": 2021,
      "qno": "简答 4",
      "type": "short",
      "prompt": "IAV负链RNA复制",
      "corePoint": "甲型流感/负链RNA复制",
      "chapter": "第22、25章",
      "coverage": "B",
      "exercisePages": "168-174, 193-197",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 11
    },
    {
      "id": "past-9a7e5dc01ef5",
      "paperId": "2021-clinical8",
      "paperLabel": "2021 临八",
      "year": 2021,
      "qno": "病例 1",
      "type": "case",
      "prompt": "埃及旅行后脓血便和里急后重：两种病原及鉴别",
      "corePoint": "肠道致病菌实验室鉴定",
      "chapter": "第7、9、10章",
      "coverage": "B",
      "exercisePages": "65-70, 85-98",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 12
    },
    {
      "id": "past-dea0d84f1eb7",
      "paperId": "2021-clinical8",
      "paperLabel": "2021 临八",
      "year": 2021,
      "qno": "病例 2",
      "type": "case",
      "prompt": "麻疹病例、病毒核酸、VZV、症状、MMR与发病回升",
      "corePoint": "麻疹病例、MMR与发病回升",
      "chapter": "第25章 呼吸道病毒",
      "coverage": "B",
      "exercisePages": "193-197",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 13
    },
    {
      "id": "past-2c539a6fe2c9",
      "paperId": "2018-preventive",
      "paperLabel": "2018 预防",
      "year": 2018,
      "qno": "名词解释 1",
      "type": "term",
      "prompt": "原核细胞型微生物",
      "corePoint": "原核细胞型微生物",
      "chapter": "绪论；第1章",
      "coverage": "A",
      "exercisePages": "12-16",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 1
    },
    {
      "id": "past-e71e044ceb5e",
      "paperId": "2018-preventive",
      "paperLabel": "2018 预防",
      "year": 2018,
      "qno": "名词解释 2",
      "type": "term",
      "prompt": "lysogenic bacterium",
      "corePoint": "溶原性细菌/温和噬菌体",
      "chapter": "第3、4章",
      "coverage": "B",
      "exercisePages": "35-44",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 2
    },
    {
      "id": "past-83e28df01f0f",
      "paperId": "2018-preventive",
      "paperLabel": "2018 预防",
      "year": 2018,
      "qno": "名词解释 3",
      "type": "term",
      "prompt": "infectious RNA",
      "corePoint": "感染性核酸/正链RNA",
      "chapter": "第22章 病毒基本性状",
      "coverage": "A",
      "exercisePages": "170-174",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 3
    },
    {
      "id": "past-4ffd47bc8f22",
      "paperId": "2018-preventive",
      "paperLabel": "2018 预防",
      "year": 2018,
      "qno": "名词解释 4",
      "type": "term",
      "prompt": "antigenic shift",
      "corePoint": "流感抗原性转变/大流行",
      "chapter": "第25章 呼吸道病毒",
      "coverage": "B",
      "exercisePages": "193-197",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 4
    },
    {
      "id": "past-f821ea2c785c",
      "paperId": "2018-preventive",
      "paperLabel": "2018 预防",
      "year": 2018,
      "qno": "名词解释 5",
      "type": "term",
      "prompt": "crossing reactivation",
      "corePoint": "交叉复活",
      "chapter": "第22章 病毒基本性状",
      "coverage": "A",
      "exercisePages": "170-174",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 5
    },
    {
      "id": "past-cb4ff47daa25",
      "paperId": "2018-preventive",
      "paperLabel": "2018 预防",
      "year": 2018,
      "qno": "X型 1",
      "type": "raw",
      "prompt": "革兰阴性菌外膜结构",
      "corePoint": "革兰阴性菌外膜结构",
      "chapter": "第1章 细菌形态与结构",
      "coverage": "B",
      "exercisePages": "16-23",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 6
    },
    {
      "id": "past-9b195b224cd9",
      "paperId": "2018-preventive",
      "paperLabel": "2018 预防",
      "year": 2018,
      "qno": "X型 2",
      "type": "raw",
      "prompt": "细菌核质错误叙述",
      "corePoint": "细菌核质的结构特点",
      "chapter": "第1章 细菌形态与结构",
      "coverage": "B",
      "exercisePages": "16-23",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 7
    },
    {
      "id": "past-281a2f333b5d",
      "paperId": "2018-preventive",
      "paperLabel": "2018 预防",
      "year": 2018,
      "qno": "X型 3",
      "type": "raw",
      "prompt": "病毒感染细胞后的结局",
      "corePoint": "病毒感染细胞的结局/CPE",
      "chapter": "第23、24章",
      "coverage": "B",
      "exercisePages": "176-191",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 8
    },
    {
      "id": "past-4ad5a9395c07",
      "paperId": "2018-preventive",
      "paperLabel": "2018 预防",
      "year": 2018,
      "qno": "X型 4",
      "type": "raw",
      "prompt": "分节段RNA病毒",
      "corePoint": "分节段RNA病毒",
      "chapter": "第22章 病毒基本性状",
      "coverage": "A",
      "exercisePages": "170-174",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 9
    },
    {
      "id": "past-baa288f02c2d",
      "paperId": "2018-preventive",
      "paperLabel": "2018 预防",
      "year": 2018,
      "qno": "X型 5",
      "type": "raw",
      "prompt": "病毒早期蛋白",
      "corePoint": "病毒早期蛋白",
      "chapter": "第22章 病毒基本性状",
      "coverage": "C",
      "exercisePages": "168-174",
      "judgment": "仅补概念，不足以单独应试",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 10
    },
    {
      "id": "past-04b3b4027963",
      "paperId": "2018-preventive",
      "paperLabel": "2018 预防",
      "year": 2018,
      "qno": "X型 6",
      "type": "raw",
      "prompt": "肠道致病菌检查的诊断意义",
      "corePoint": "肠道致病菌实验室鉴定",
      "chapter": "第7、9、10章",
      "coverage": "B",
      "exercisePages": "65-70, 85-98",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 11
    },
    {
      "id": "past-e9b706a6aa46",
      "paperId": "2018-preventive",
      "paperLabel": "2018 预防",
      "year": 2018,
      "qno": "X型 7",
      "type": "raw",
      "prompt": "发酵乳糖产酸产气的细菌",
      "corePoint": "肠道菌乳糖发酵",
      "chapter": "第9章 肠杆菌科",
      "coverage": "A",
      "exercisePages": "85-92",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 12
    },
    {
      "id": "past-5cbc36663039",
      "paperId": "2018-preventive",
      "paperLabel": "2018 预防",
      "year": 2018,
      "qno": "X型 8",
      "type": "raw",
      "prompt": "抗生素作用机制",
      "corePoint": "抗菌药物作用机制",
      "chapter": "第5章 细菌耐药性",
      "coverage": "A",
      "exercisePages": "45-48",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 13
    },
    {
      "id": "past-85134694320e",
      "paperId": "2018-preventive",
      "paperLabel": "2018 预防",
      "year": 2018,
      "qno": "X型 9",
      "type": "raw",
      "prompt": "两次入血且以内毒素致病",
      "corePoint": "伤寒沙门菌的致病过程",
      "chapter": "第9章 肠杆菌科",
      "coverage": "B",
      "exercisePages": "85-92",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 14
    },
    {
      "id": "past-e19d6ea8393e",
      "paperId": "2018-preventive",
      "paperLabel": "2018 预防",
      "year": 2018,
      "qno": "X型 10",
      "type": "raw",
      "prompt": "显微镜下成双排列的细菌",
      "corePoint": "双球菌的形态鉴别",
      "chapter": "第8章 球菌",
      "coverage": "A",
      "exercisePages": "71-84",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 15
    },
    {
      "id": "past-aa7dbc812a27",
      "paperId": "2018-preventive",
      "paperLabel": "2018 预防",
      "year": 2018,
      "qno": "X型 11",
      "type": "raw",
      "prompt": "细菌感染的免疫学检测",
      "corePoint": "细菌感染的免疫学检测",
      "chapter": "第7章 检测与防治",
      "coverage": "B",
      "exercisePages": "65-70",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 16
    },
    {
      "id": "past-0f7542ab9675",
      "paperId": "2018-preventive",
      "paperLabel": "2018 预防",
      "year": 2018,
      "qno": "X型 12",
      "type": "raw",
      "prompt": "病毒进入细胞的方式",
      "corePoint": "病毒穿入细胞方式",
      "chapter": "第22章 病毒基本性状",
      "coverage": "B",
      "exercisePages": "168-174",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 17
    },
    {
      "id": "past-0f52aa18c3fd",
      "paperId": "2018-preventive",
      "paperLabel": "2018 预防",
      "year": 2018,
      "qno": "X型 13",
      "type": "raw",
      "prompt": "结核菌素试验假阴性",
      "corePoint": "结核菌素试验及假阴性",
      "chapter": "第13章 分枝杆菌属",
      "coverage": "B",
      "exercisePages": "108-114",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 18
    },
    {
      "id": "past-91a1267a9ed9",
      "paperId": "2018-preventive",
      "paperLabel": "2018 预防",
      "year": 2018,
      "qno": "X型 14",
      "type": "raw",
      "prompt": "HSV-1潜伏部位",
      "corePoint": "HSV原发、潜伏与复发",
      "chapter": "第31章 疱疹病毒",
      "coverage": "A",
      "exercisePages": "232-237",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 19
    },
    {
      "id": "past-c1ac2bd5e38b",
      "paperId": "2018-preventive",
      "paperLabel": "2018 预防",
      "year": 2018,
      "qno": "X型 15",
      "type": "raw",
      "prompt": "质粒错误叙述",
      "corePoint": "质粒的结构、复制与转移",
      "chapter": "第1、4章",
      "coverage": "A",
      "exercisePages": "16-23, 39-44",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 20
    },
    {
      "id": "past-17bf7ad879aa",
      "paperId": "2018-preventive",
      "paperLabel": "2018 预防",
      "year": 2018,
      "qno": "X型 16",
      "type": "raw",
      "prompt": "草绿色溶血及胆汁溶菌阳性菌",
      "corePoint": "肺炎链球菌与胆汁溶菌试验",
      "chapter": "第8章 球菌",
      "coverage": "A",
      "exercisePages": "73-80",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 21
    },
    {
      "id": "past-221afae6ea60",
      "paperId": "2018-preventive",
      "paperLabel": "2018 预防",
      "year": 2018,
      "qno": "X型 17",
      "type": "raw",
      "prompt": "金葡菌化脓感染局限化原因",
      "corePoint": "凝固酶",
      "chapter": "第8章 球菌",
      "coverage": "A",
      "exercisePages": "71-81",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 22
    },
    {
      "id": "past-680250c1e88d",
      "paperId": "2018-preventive",
      "paperLabel": "2018 预防",
      "year": 2018,
      "qno": "X型 18",
      "type": "raw",
      "prompt": "虫媒病毒",
      "corePoint": "虫媒病毒",
      "chapter": "第29章 虫媒病毒",
      "coverage": "B",
      "exercisePages": "220-225",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 23
    },
    {
      "id": "past-70182ce55c5f",
      "paperId": "2018-preventive",
      "paperLabel": "2018 预防",
      "year": 2018,
      "qno": "X型 19",
      "type": "raw",
      "prompt": "流感病毒血凝素错误叙述",
      "corePoint": "流感病毒HA/NA",
      "chapter": "第25章 呼吸道病毒",
      "coverage": "B",
      "exercisePages": "193-197",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 24
    },
    {
      "id": "past-0eed86594f06",
      "paperId": "2018-preventive",
      "paperLabel": "2018 预防",
      "year": 2018,
      "qno": "X型 21",
      "type": "raw",
      "prompt": "可引起肺部感染的病原体",
      "corePoint": "支原体/衣原体等肺部感染",
      "chapter": "第18、20章",
      "coverage": "C",
      "exercisePages": "144-160",
      "judgment": "仅补概念，不足以单独应试",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 25
    },
    {
      "id": "past-0771fb1dee8e",
      "paperId": "2018-preventive",
      "paperLabel": "2018 预防",
      "year": 2018,
      "qno": "X型 22",
      "type": "raw",
      "prompt": "HIV病原体特征",
      "corePoint": "HIV结构、潜伏期与致病",
      "chapter": "第32章 逆转录病毒",
      "coverage": "B",
      "exercisePages": "238-244",
      "judgment": "可训练核心考点",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 26
    },
    {
      "id": "past-54a9f5e8165b",
      "paperId": "2018-preventive",
      "paperLabel": "2018 预防",
      "year": 2018,
      "qno": "X型 23",
      "type": "raw",
      "prompt": "与细菌致病性强弱无关的因素",
      "corePoint": "细菌毒力与致病物质",
      "chapter": "第6章 细菌感染与免疫",
      "coverage": "A",
      "exercisePages": "50-61",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 27
    },
    {
      "id": "past-a770c04d0d1d",
      "paperId": "2018-preventive",
      "paperLabel": "2018 预防",
      "year": 2018,
      "qno": "X型 24",
      "type": "raw",
      "prompt": "美容除皱所用细菌毒素",
      "corePoint": "肉毒毒素作用部位与临床表现",
      "chapter": "第12章 厌氧性细菌",
      "coverage": "A",
      "exercisePages": "102-106",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 28
    },
    {
      "id": "past-521e4de513ee",
      "paperId": "2018-preventive",
      "paperLabel": "2018 预防",
      "year": 2018,
      "qno": "X型 25",
      "type": "raw",
      "prompt": "非细胞型微生物所致疾病",
      "corePoint": "非细胞型微生物",
      "chapter": "绪论；第22章",
      "coverage": "A",
      "exercisePages": "12-15, 168-174",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 29
    },
    {
      "id": "past-fac0fd48a871",
      "paperId": "2018-preventive",
      "paperLabel": "2018 预防",
      "year": 2018,
      "qno": "简答 1",
      "type": "short",
      "prompt": "影印培养试验及意义",
      "corePoint": "影印培养试验",
      "chapter": "习题集未检出",
      "coverage": "D",
      "exercisePages": "未检出",
      "judgment": "习题集无有效覆盖",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 30
    },
    {
      "id": "past-c107adc6862f",
      "paperId": "2018-preventive",
      "paperLabel": "2018 预防",
      "year": 2018,
      "qno": "简答 2",
      "type": "short",
      "prompt": "正链与负链RNA病毒生物合成异同",
      "corePoint": "正链/负链RNA病毒生物合成",
      "chapter": "第22章 病毒基本性状",
      "coverage": "C",
      "exercisePages": "168-174",
      "judgment": "仅补概念，不足以单独应试",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 31
    },
    {
      "id": "past-9be611d3cc51",
      "paperId": "2018-preventive",
      "paperLabel": "2018 预防",
      "year": 2018,
      "qno": "简答 3",
      "type": "short",
      "prompt": "AIDS鸡尾酒疗法方案构成",
      "corePoint": "AIDS联合抗逆转录病毒治疗",
      "chapter": "第32章 逆转录病毒",
      "coverage": "C",
      "exercisePages": "238-244",
      "judgment": "仅补概念，不足以单独应试",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 32
    },
    {
      "id": "past-55e2bbe8bcce",
      "paperId": "2018-preventive",
      "paperLabel": "2018 预防",
      "year": 2018,
      "qno": "病例 1",
      "type": "case",
      "prompt": "乙肝五项“大三阳”、阳性指标意义及HBV核酸特点",
      "corePoint": "HBV血清标志物",
      "chapter": "第28章 肝炎病毒",
      "coverage": "A",
      "exercisePages": "211-219",
      "judgment": "同题训练充分",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 33
    },
    {
      "id": "past-dc6b06b3aecc",
      "paperId": "2018-preventive",
      "paperLabel": "2018 预防",
      "year": 2018,
      "qno": "病例 2",
      "type": "case",
      "prompt": "COVID-19防控难点与解决措施",
      "corePoint": "SARS-CoV-2/COVID-19",
      "chapter": "习题集未检出",
      "coverage": "D",
      "exercisePages": "未检出",
      "judgment": "习题集无有效覆盖",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx",
      "sourceNote": "历年回忆题摘要；完整回忆原文见汇编第六部分",
      "rowIndex": 34
    }
  ],
  "rawItems": [
    {
      "id": "raw-35022aaa07b9",
      "paperLabel": "2018 预防",
      "qno": "X型 20",
      "rawText": "图片箭头所示细菌特殊结构",
      "issue": "题意不足或原始材料缺失",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx"
    },
    {
      "id": "raw-e709d26d6703",
      "paperLabel": "2022 预防",
      "qno": "病例 1",
      "rawText": "病例题1内容未回忆",
      "issue": "题意不足或原始材料缺失",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx"
    },
    {
      "id": "raw-08799e7ff6ae",
      "paperLabel": "2022 预防",
      "qno": "病例 2",
      "rawText": "病例题2内容未回忆",
      "issue": "题意不足或原始材料缺失",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx"
    },
    {
      "id": "raw-245b0887b463",
      "paperLabel": "2023 预防/法医",
      "qno": "A1 附",
      "rawText": "动物源性细菌/虫媒病毒全英文题，题意不完整",
      "issue": "题意不足或原始材料缺失",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx"
    },
    {
      "id": "raw-91fd10583882",
      "paperLabel": "2023 预防/法医",
      "qno": "A2 2",
      "rawText": "英文病例题未回忆",
      "issue": "题意不足或原始材料缺失",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx"
    },
    {
      "id": "raw-124061cc78aa",
      "paperLabel": "2023 预防/法医",
      "qno": "X型 3",
      "rawText": "原题未回忆",
      "issue": "题意不足或原始材料缺失",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx"
    },
    {
      "id": "raw-8c0913d8f993",
      "paperLabel": "2023 预防/法医",
      "qno": "X型 4",
      "rawText": "原题未回忆",
      "issue": "题意不足或原始材料缺失",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx"
    },
    {
      "id": "raw-075bd78b4bb8",
      "paperLabel": "2023 预防/法医",
      "qno": "X型 5",
      "rawText": "原题未回忆",
      "issue": "题意不足或原始材料缺失",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx"
    },
    {
      "id": "raw-35ed95e43de5",
      "paperLabel": "2021 临八",
      "qno": "A2 38",
      "rawText": "原题未回忆",
      "issue": "题意不足或原始材料缺失",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx"
    },
    {
      "id": "raw-f828bb246096",
      "paperLabel": "2022 临五",
      "qno": "A1 6",
      "rawText": "腹部脓肿病例题意不清",
      "issue": "题意不足或原始材料缺失",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx"
    },
    {
      "id": "raw-f7a3f9262ce6",
      "paperLabel": "2022 临五",
      "qno": "A1 15",
      "rawText": "分节段腹泻病毒，题意不完整",
      "issue": "题意不足或原始材料缺失",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx"
    },
    {
      "id": "raw-579c551a86d7",
      "paperLabel": "2022 临五",
      "qno": "名词解释 3",
      "rawText": "原题未回忆",
      "issue": "题意不足或原始材料缺失",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx"
    },
    {
      "id": "raw-6228ea705225",
      "paperLabel": "2022 临五",
      "qno": "名词解释 4",
      "rawText": "原题未回忆",
      "issue": "题意不足或原始材料缺失",
      "source": "医学微生物学C历年题汇编与习题集覆盖分析.docx"
    }
  ]
};
